name: Build Database Project

on:
  push:
    branches: [ "main" ]
    paths:
      - 'BikeMatrixDatabase/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'BikeMatrixDatabase/**'

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore BikeMatrixDatabase\BikeMatrixDatabase.sln

      - name: Build project
        run: msbuild BikeMatrixDatabase\BikeMatrixDatabase.sln /p:Configuration=Release /p:RestorePackages=false
